### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by kindlehl** [pwittchen/spotify-cli-linux#39]
I get an error when I try to install this software with pip or pip3

The error is:
```bash
Collecting spotify-cli-linux
  Using cached https://files.pythonhosted.org/packages/5d/98/0cb8af6dc7be4b1f893d32467e1384b6b96b477b234785b098bd6a38b150/spotify-cli-linux-1.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5xhxsnlp/spotify-cli-linux/setup.py", line 4, in <module>
        from spotifycli.spotifycli import __doc__
      File "/tmp/pip-install-5xhxsnlp/spotify-cli-linux/spotifycli/spotifycli.py", line 15, in <module>
        from version import __version__
    ImportError: No module named 'version'
    
    ----------------------------------------

```

**Comment by pwittchen** [comment]
Please try to use `sudo` command before `pip` or `pip3` and tell me if it helps.

**Comment by kindlehl** [comment]
@pwittchen It does not

**Comment by pwittchen** [comment]
Ok, You can try another way to install it:

```
sudo python3 -m pip install spotify-cli-linux
```

**Comment by kindlehl** [comment]
That worked!

**Comment by pwittchen** [comment]
Great! :-D :+1:
