### ISSUE TITLE
ModuleNotFoundError: No module named 'lyricwikia'

### ISSUE THREAD

**Issue by jayypluss** [pwittchen/spotify-cli-linux#41]
I get this error message when trying to install it with `sudo pip install spotify-cli-linux`:

```
➜  ~ sudo pip install spotify-cli-linux                
[sudo] password for jonathanfk: 
Collecting spotify-cli-linux
  Using cached https://files.pythonhosted.org/packages/5d/98/0cb8af6dc7be4b1f893d32467e1384b6b96b477b234785b098bd6a38b150/spotify-cli-linux-1.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-u6pxbapq/spotify-cli-linux/setup.py", line 4, in <module>
        from spotifycli.spotifycli import __doc__
      File "/tmp/pip-install-u6pxbapq/spotify-cli-linux/spotifycli/spotifycli.py", line 9, in <module>
        import lyricwikia
    ModuleNotFoundError: No module named 'lyricwikia'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-u6pxbapq/spotify-cli-linux/

```

About system:

![image](https://user-images.githubusercontent.com/17395606/55488753-04fd9c00-5607-11e9-898d-e6c5669e501e.png)

**Comment by pwittchen** [comment]
Try to type:

```
sudo python3 -m pip install spotify-cli-linux
```

If it won't help, try to type:

```
sudo pip install lyricwikia
```

**Comment by jayypluss** [comment]
Worked after installing lyricwikia with `sudo pip install lyricwikia`. Thanks!

**Comment by pwittchen** [comment]
Good. It's strange that it wasn't downloaded automatically as `lyricwikia` is defined as a project dependency.
